// Generated by Wrangler on Wed Feb 05 2025 19:14:33 GMT+0100 (heure normale d’Europe centrale)
// by running `wrangler types`

interface Env {
	keyValueStore: KVNamespace;
	PLUGIN_PARENT_DOMAIN: "plugins.framercdn.com";
	CLIENT_ID: string;
	CLIENT_SECRET: string;
	PLUGIN_ID: string;
	REDIRECT_URI: string;
	AUTHORIZE_ENDPOINT: string;
	TOKEN_ENDPOINT: string;
	SCOPE: string;
}
